name: Life Time Value Conference 2017

exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor']
permalink: /:year/:title/

sass:
  style: :compressed

collections:
  misc:
    output: true
    permalink: /misc/:path/

assets:
  autoprefixer:
    browsers:
      - "last 2 versions"
      - "IE > 9"
